/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.gui.panels.components;

import app.models.order.OrderStatus;

public class ChangeOrderStatusGlassPane extends javax.swing.JPanel {


    public ChangeOrderStatusGlassPane(OrderStatus status) {
        initComponents();
        setSize(1200,600);
        updatedStatus.setText(OrderStatus.getSimpleName(status));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        updatedStatus = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(100, 200, 100, 200));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Rajdhani SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>   <p style=\"text-align:center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque auctor nibh ac dolor vehicula dapibus. Pellentesque vitae pretium nulla. Aenean in tortor augue. Suspendisse sit amet dolor a ligula elementum venenatis. Nunc sed quam sed est vestibulum laoreet. Vestibulum sit amet consectetur odio. Sed in ligula enim. Nulla facilisi. Duis. </p> </html> ");

        updatedStatus.setFont(new java.awt.Font("Rajdhani", 1, 36)); // NOI18N
        updatedStatus.setForeground(new java.awt.Color(255, 255, 255));
        updatedStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatedStatus.setText("KITCHEN APPROVED");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatedStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(updatedStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gui/resources/images/glassPane.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updatedStatus;
    // End of variables declaration//GEN-END:variables
}
