/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.gui.panels.odrernew;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class customizedFoodCard extends javax.swing.JPanel {


    public customizedFoodCard(String FoodName,orderNewBase PARENT) {
        initComponents();
        customizedFoodTitle.setText("CUSTOMIZED "+ FoodName);
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                PARENT.orderNewContentPanel.removeAll();
                PARENT.orderNewContentPanel.add(new singleFoodView());
                PARENT.orderNewContentPanel.revalidate();
                PARENT.orderNewContentPanel.repaint();
            }
        
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contetHoderPanel = new javax.swing.JPanel();
        customizedFoodTitle = new javax.swing.JLabel();
        assignments_label6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 196, 216)));
        setLayout(new java.awt.BorderLayout());

        contetHoderPanel.setBackground(new java.awt.Color(253, 232, 240));
        contetHoderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));
        contetHoderPanel.setPreferredSize(new java.awt.Dimension(230, 120));

        customizedFoodTitle.setFont(new java.awt.Font("Rajdhani SemiBold", 0, 14)); // NOI18N
        customizedFoodTitle.setForeground(new java.awt.Color(156, 15, 72));
        customizedFoodTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customizedFoodTitle.setText("<html><p>CUSTOMIZED BURGER </p></html>");
        customizedFoodTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));

        assignments_label6.setFont(new java.awt.Font("Rajdhani SemiBold", 0, 10)); // NOI18N
        assignments_label6.setForeground(new java.awt.Color(102, 102, 102));
        assignments_label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        assignments_label6.setText("<html>   <p style=\"text-align:center\">     Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.    </p> </html> ");
        assignments_label6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 3, 0, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/gui/resources/images/icons8-plus-70.png"))); // NOI18N

        javax.swing.GroupLayout contetHoderPanelLayout = new javax.swing.GroupLayout(contetHoderPanel);
        contetHoderPanel.setLayout(contetHoderPanelLayout);
        contetHoderPanelLayout.setHorizontalGroup(
            contetHoderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contetHoderPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(contetHoderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customizedFoodTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(assignments_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        contetHoderPanelLayout.setVerticalGroup(
            contetHoderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contetHoderPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customizedFoodTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(assignments_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(contetHoderPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assignments_label6;
    private javax.swing.JPanel contetHoderPanel;
    private javax.swing.JLabel customizedFoodTitle;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
