/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package app.gui.panels.odrernew;

import app.models.database.Database;
import app.models.food.Food;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Titu
 */
public class foodBaseItemsPanel extends javax.swing.JPanel {

    private final ArrayList<Food> foodList;

    public foodBaseItemsPanel(int row, String foodCategory, orderNewBase PARENT) {
        initComponents();
        foodList = Database.PredefinedData.getFoodList();

        int horizontalGap = 260;
        int verticalGap = 330;

        int xBound = 0;
        int yBound = 0;

        for (int i = 0; i < row; i++) {
            for (int j = 0; j < 4; j++) {
                JPanel foodPanel;

                if (i == 0 && j == 0) {
                    foodPanel = new customizedFoodCard(foodCategory, PARENT);
                } else {
                    foodPanel = new verticalCard(foodList.get(j));
                }

                foodPanel.setBounds(xBound, yBound, 230, 300);
                add(foodPanel);

                xBound += horizontalGap;
            }

            xBound = 0;
            yBound += verticalGap;
        }

        setPreferredSize(new Dimension(1050, (verticalGap * row) - 30));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 40));
        setPreferredSize(new java.awt.Dimension(1050, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 201, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
